# Generated by Django 3.0.5 on 2021-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210110_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pone',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
