# Generated by Django 3.0.5 on 2021-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210111_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
