# Generated by Django 3.0.5 on 2021-01-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210111_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
