# Generated by Django 3.0.5 on 2020-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('details', models.CharField(max_length=500)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
