# Generated by Django 3.0.5 on 2020-05-04 12:19

from django.db import migrations, models
import navy.models


class Migration(migrations.Migration):

    dependencies = [
        ('navy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navyemployee',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/', validators=[navy.models.validate_image]),
        ),
    ]
